logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
#    org.springframework.web: trace
    org.springframework.web: info
# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 5
      # 配置最大线程数
      max_pool_size: 5
      # 配置队列大小
      queue_capacity: 99999
      name:
        # 配置线程池中的线程的名称前缀
        prefix: async-service-